name: Upload
on:
  release:
    types: [published]

jobs:
  upload:
    runs-on: ubuntu-latest

    env:
      SYMPY_USE_CACHE: "no"

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Build and install Strawberry Fields
        run: |
          python -m pip install --upgrade pip wheel
          python setup.py bdist_wheel
          pip install dist/StrawberryFields*.whl

      - name: Install test dependencies
        run: |
          pip install -r requirements-ci.txt
          pip install wheel pytest pytest-cov pytest-mock --upgrade

      - name: Run tests
        run: |
          python -m pytest tests -p no:warnings --randomly-seed=42 --tb=native

      - name: Publish
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.PYPI }}
